# Generated by Django 5.0.4 on 2025-10-16 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dui',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
