# Generated by Django 5.0.4 on 2025-11-10 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('stela', '0003_remove_empresa_usuario_empresa_usuario'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useraccess',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='companyId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stela.empresa'),
        ),
        migrations.AlterField(
            model_name='useraccess',
            name='optionId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.optionform'),
        ),
        migrations.AlterField(
            model_name='useraccess',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='useraccess',
            unique_together={('userId', 'optionId', 'companyId')},
        ),
    ]
