# Generated by Django 5.1.3 on 2025-11-07 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id_balance', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_balance', models.CharField(choices=[('BAL', 'Balance'), ('RES', 'Resultados')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id_cuenta', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=180)),
                ('aparece_en_balance', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LineaEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('BAL', 'Balance'), ('RES', 'Resultados')], max_length=3)),
                ('clave', models.CharField(max_length=64, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('base_vertical', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RatioDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=64, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('formula', models.TextField()),
                ('porcentaje', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ciiu',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('nivel', models.IntegerField()),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='stela.ciiu')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('haber', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='stela.balance')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stela.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('nit', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('nrc', models.CharField(max_length=8, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('ciiu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas_asociadas', to='stela.ciiu')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id_catalogo', models.AutoField(primary_key=True, serialize=False)),
                ('anio_catalogo', models.IntegerField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogos', to='stela.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'anio_catalogo')},
            },
        ),
        migrations.AddField(
            model_name='balance',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stela.empresa'),
        ),
        migrations.CreateModel(
            name='GrupoCuenta',
            fields=[
                ('id_grupoCuenta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('naturaleza', models.CharField(choices=[('A', 'Activo'), ('L', 'Pasivo'), ('P', 'Patrimonio'), ('I', 'Ingreso'), ('G', 'Gasto')], max_length=1)),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='stela.catalogo')),
            ],
        ),
        migrations.AddField(
            model_name='cuenta',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='stela.grupocuenta'),
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id_periodo', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('fecha_cerrado', models.DateField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='stela.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'anio', 'mes')},
            },
        ),
        migrations.AddField(
            model_name='balance',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stela.periodo'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('mes_venta', models.DateField()),
                ('saldo_venta', models.FloatField()),
                ('anio', models.IntegerField()),
                ('proyeccion', models.BooleanField()),
                ('empresa', models.ForeignKey(max_length=4, on_delete=django.db.models.deletion.CASCADE, to='stela.empresa')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cuenta',
            unique_together={('grupo', 'codigo')},
        ),
        migrations.CreateModel(
            name='MapeoCuentaLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signo', models.SmallIntegerField(default=1)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stela.cuenta')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stela.lineaestado')),
            ],
            options={
                'unique_together': {('cuenta', 'linea')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='balance',
            unique_together={('empresa', 'periodo', 'tipo_balance')},
        ),
        migrations.CreateModel(
            name='ResultadoRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stela.empresa')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stela.periodo')),
                ('ratio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stela.ratiodef')),
            ],
            options={
                'unique_together': {('empresa', 'periodo', 'ratio')},
            },
        ),
    ]
