# Generated by Django 5.0.4 on 2025-11-11 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id_balance', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_balance', models.CharField(choices=[('BAL', 'Balance'), ('RES', 'Resultados')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id_cuenta', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=180)),
                ('aparece_en_balance', models.BooleanField(default=True)),
                ('er_bloque', models.CharField(blank=True, choices=[('', 'Sin bloque'), ('VENTAS_NETAS', 'Ventas Netas'), ('COSTO_NETO_VENTAS', 'Costo Neto de Ventas'), ('GASTOS_OPERATIVOS', 'Gastos Operativos'), ('OTROS_INGRESOS', 'Otros Ingresos'), ('OTROS_GASTOS', 'Otros Gastos'), ('GASTO_FINANCIERO', 'Gasto Financiero'), ('IMPUESTO_SOBRE_LA_RENTA', 'Impuesto sobre la Renta')], default='', help_text='Bloque del Estado de Resultados al que pertenece esta cuenta', max_length=50, null=True)),
                ('bg_bloque', models.CharField(blank=True, choices=[('', 'Sin bloque'), ('ACTIVO_CORRIENTE', 'Activo Corriente'), ('ACTIVO_NO_CORRIENTE', 'Activo No Corriente'), ('PASIVO_CORRIENTE', 'Pasivo Corriente'), ('PASIVO_NO_CORRIENTE', 'Pasivo No Corriente'), ('PATRIMONIO', 'Patrimonio')], default='', help_text='Bloque del Balance General donde se mostrará esta cuenta', max_length=50, null=True)),
                ('ratio_tag', models.CharField(blank=True, choices=[('', 'Sin tag'), ('EFECTIVO', 'Efectivo (Caja + Bancos + Equivalentes)'), ('CUENTAS_POR_COBRAR', 'Cuentas por Cobrar'), ('INVENTARIOS', 'Inventarios'), ('ACTIVO_CORRIENTE', 'Activo Corriente'), ('ACTIVO_TOTAL', 'Activo Total'), ('ACTIVO_FIJO_NETO', 'Activo Fijo Neto'), ('PASIVO_CORRIENTE', 'Pasivo Corriente'), ('PASIVO_TOTAL', 'Pasivo Total'), ('PATRIMONIO_TOTAL', 'Patrimonio Total'), ('VENTAS_NETAS', 'Ventas Netas'), ('COSTO_VENTAS', 'Costo de Ventas'), ('COMPRAS', 'Compras'), ('GASTOS_OPERATIVOS', 'Gastos Operativos'), ('OTROS_INGRESOS', 'Otros Ingresos'), ('OTROS_GASTOS', 'Otros Gastos'), ('GASTO_FINANCIERO', 'Gasto Financiero'), ('IMPUESTO_RENTA', 'Impuesto sobre la Renta'), ('UTILIDAD_OPERATIVA', 'Utilidad Operativa (EBIT)'), ('UTILIDAD_NETA', 'Utilidad Neta'), ('DEPRECIACION', 'Depreciación'), ('AMORTIZACION', 'Amortización'), ('SERVICIO_DEUDA', 'Servicio de Deuda')], default='', help_text='Tag constante para cálculo de ratios. Múltiples cuentas pueden tener el mismo tag y se sumarán automáticamente.', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LineaEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('BAL', 'Balance'), ('RES', 'Resultados')], max_length=3)),
                ('clave', models.CharField(max_length=64, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('base_vertical', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RatioDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=64, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('formula', models.TextField()),
                ('porcentaje', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ciiu',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('nivel', models.IntegerField()),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='stela.ciiu')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('haber', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='stela.balance')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stela.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('nit', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('nrc', models.CharField(max_length=8, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('ciiu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas_asociadas', to='stela.ciiu')),
                ('usuario', models.ManyToManyField(related_name='empresas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id_catalogo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catalogo', to='stela.empresa')),
            ],
            options={
                'verbose_name': 'Catálogo',
                'verbose_name_plural': 'Catálogos',
            },
        ),
        migrations.AddField(
            model_name='balance',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stela.empresa'),
        ),
        migrations.CreateModel(
            name='GrupoCuenta',
            fields=[
                ('id_grupoCuenta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('naturaleza', models.CharField(choices=[('Activo', 'Activo'), ('Pasivo', 'Pasivo'), ('Patrimonio', 'Patrimonio'), ('Ingreso', 'Ingreso'), ('Gasto', 'Gasto')], max_length=20)),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='stela.catalogo')),
            ],
        ),
        migrations.AddField(
            model_name='cuenta',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='stela.grupocuenta'),
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id_periodo', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('fecha_cerrado', models.DateField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='stela.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'anio', 'mes')},
            },
        ),
        migrations.AddField(
            model_name='balance',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stela.periodo'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('mes_venta', models.DateField()),
                ('saldo_venta', models.FloatField()),
                ('anio', models.IntegerField()),
                ('proyeccion', models.BooleanField()),
                ('empresa', models.ForeignKey(max_length=4, on_delete=django.db.models.deletion.CASCADE, to='stela.empresa')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cuenta',
            unique_together={('grupo', 'codigo')},
        ),
        migrations.CreateModel(
            name='MapeoCuentaLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signo', models.SmallIntegerField(default=1)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stela.cuenta')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stela.lineaestado')),
            ],
            options={
                'unique_together': {('cuenta', 'linea')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='balance',
            unique_together={('empresa', 'periodo', 'tipo_balance')},
        ),
        migrations.CreateModel(
            name='ResultadoRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stela.empresa')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stela.periodo')),
                ('ratio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stela.ratiodef')),
            ],
            options={
                'unique_together': {('empresa', 'periodo', 'ratio')},
            },
        ),
    ]
