# Generated by Django 5.1.3 on 2025-10-31 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciuu',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('nivel', models.IntegerField()),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='stela.ciuu')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('nit', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('nrc', models.CharField(max_length=8, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('idCiiu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stela.ciuu')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('mes_venta', models.DateField()),
                ('saldo_venta', models.FloatField()),
                ('anio', models.IntegerField()),
                ('proyeccion', models.BooleanField()),
                ('empresa', models.ForeignKey(max_length=4, on_delete=django.db.models.deletion.CASCADE, to='stela.empresa')),
            ],
        ),
    ]
