# Generated by Django 5.1.3 on 2025-11-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stela', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nit',
            field=models.CharField(max_length=17, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(max_length=9),
        ),
    ]
