# Generated by Django 5.0.4 on 2025-10-27 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stela', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='userId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('mes_venta', models.DateField()),
                ('saldo_venta', models.FloatField()),
                ('anio', models.IntegerField()),
                ('proyeccion', models.BooleanField()),
                ('empresa', models.ForeignKey(max_length=4, on_delete=django.db.models.deletion.CASCADE, to='stela.empresa')),
            ],
        ),
    ]
