# Generated by Django 5.0.4 on 2025-10-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stela', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciuu',
            name='codigo',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
