# Generated by Django 5.0.4 on 2025-11-10 01:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stela', '0002_alter_catalogo_and_add_ratio_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='usuario',
        ),
        migrations.AddField(
            model_name='empresa',
            name='usuario',
            field=models.ManyToManyField(related_name='empresas', to=settings.AUTH_USER_MODEL),
        ),
    ]
