# Generated by Django 5.1.3 on 2025-11-11 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stela', '0002_alter_catalogo_and_add_ratio_tag'),
    ]

    operations = [
        # Renombrar la columna idCiiu_id a ciiu_id para que coincida con el modelo
        # SQLite 3.25+ soporta RENAME COLUMN
        migrations.RunSQL(
            sql="ALTER TABLE stela_empresa RENAME COLUMN idCiiu_id TO ciiu_id;",
            reverse_sql="ALTER TABLE stela_empresa RENAME COLUMN ciiu_id TO idCiiu_id;",
        ),
    ]

