# Generated by Django 5.0.4 on 2025-11-09 23:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stela', '0002_alter_catalogo_and_add_ratio_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='usuarios_adicionales',
            field=models.ManyToManyField(blank=True, related_name='empresas_adicionales', to=settings.AUTH_USER_MODEL),
        ),
    ]
