# Generated by Django 5.0.4 on 2025-11-09 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stela', '0003_empresa_usuarios_adicionales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='usuarios_adicionales',
            new_name='usuarios',
        ),
    ]
